### ISSUE TITLE
Can running GUI

### ISSUE THREAD

**Issue by Alexbabylon** [Stability-AI/generative-models#192]
hi 
anyone has this issue please help.
<img width="766" alt="2023-11-28_0-35-40" src="https://github.com/Stability-AI/generative-models/assets/128872360/ef7c0fe6-b9fa-43f4-b32e-9c45bd6e790e">

**Comment by toomanydev** [comment]
Easiest fix is to move scripts/demo/video_sampling.py to the root of the repo and run it from there instead.

**Comment by Alexbabylon** [comment]
i appreacite your time answering ,,, what you mean move it to (root) you mean ..
<img width="567" alt="2023-11-29_5-29-30" src="https://github.com/Stability-AI/generative-models/assets/128872360/4d76e1a8-d715-4fed-ba47-8ff21e7b33c3">
move it to main folder of video generation ?

**Comment by toomanydev** [comment]
Cut and paste video_sampling into the generative-models folder, yes.

That said, I had difficulty using the Streamlit UI (it generated one frame and then stopped).
If you do too, consider using the other script "generative-models/scripts/sampling/simple_video_sample.py" (you'll need to set the variables such as input image by editing the script itself), which I found easier to use. It will also need moving to the generative-models folder.

**Comment by rudisimo** [comment]
@Alexbabylon a simpler fix is to run `streamlit` as a module, like so:

```
python -m streamlit run scripts/demo/video_sampling.py
```

**Comment by Alexbabylon** [comment]
thank you guys its Works! i appreciate your time rudisimo & toomanydev for responding .
