### ISSUE TITLE
Cannot install on Debian 12. It says "error: casting `&T` to `&mut T` is undefined behavior" during requirements installation.

### ISSUE THREAD

**Issue by Developer-42** [Stability-AI/generative-models#271]
I installed Rust using `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`, because the last command gave an error that it needs a Rust compiler. I am using python3.11, but I don't think that it causes the problem.

So overall I ran the following:
```
git clone https://github.com/Stability-AI/generative-models.git
cd generative-models
python3 -m venv .pt2
source .pt2/bin/activate
pip3 install -r requirements/pt2.txt
```

The actual error is near the end of the file: [terminal_output_pt2.txt](https://github.com/Stability-AI/generative-models/files/13940907/terminal_output_pt2.txt)

Any help is appreciated.

**Comment by tafseer-khan** [comment]
Its a version compatibility issue, quick answer is to update some versions in `requirements/pt2.txt`

`tokenizers==0.12.1` -> `tokenizers>=0.14.1`
`transformers==4.19.1` -> `transformers>=4.36`

**Comment by Developer-42** [comment]
Thanks to @tafseer-khan I was able to solve this.
