### ISSUE TITLE
Some typos in Paper

### ISSUE THREAD

**Issue by hu-po** [Stability-AI/generative-models#30]
Love the research, keep doing the good work! I found some potential typos in the paper:

This should be PSNR:
![image](https://github.com/Stability-AI/generative-models/assets/8493427/e9d1ed22-b14f-4f5f-b603-f8c539b3a460)

Double function?
![image](https://github.com/Stability-AI/generative-models/assets/8493427/804a5a0b-f0e7-4d3c-a240-effd49dfe0c4)

If you are curious I'd love a [review of my review of this paper](https://www.youtube.com/live/kHYxM6RG_rU). :pray:

**Comment by jenuk** [comment]
Thank you, I have updated this. The changes will be uploaded at some point in the future.
