### ISSUE TITLE
img2img

### ISSUE THREAD

**Issue by terekita** [Stability-AI/generative-models#31]
I tried passing in an image as I have with earlier models:
images = pipe(prompt=prompt, image=init_img).images[0], 
and learned that this doesn't work. 

Is there a way to do img2img operations with this model?

**Comment by prasad-shembekar** [comment]
i have not worked on this model before sharing reference [blog](https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/img2img) hope it will help you!

**Comment by woctezuma** [comment]
It is supposed to work.

https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_xl#imagetoimage
