### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for LatentDiffusion

### ISSUE THREAD

**Issue by zhongfuxiao** [Stability-AI/generative-models#34]
dear guys:
when i change model to sdxl, i got error below
 raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
        size mismatch for model.diffusion_model.time_embed.0.weight: copying a param with shape torch.Size([1536, 384]) from checkpoint, the shape in current model is torch.Size([1280, 320])
………………………………………………………………
how can I resolve this problem?

**Comment by GZ315200** [comment]
same

**Comment by Ricaardo** [comment]
same

**Comment by pixeladdikt** [comment]
Yo! Same error and I've copied the latest YAML files for Base & Refiner. Using RunPod. Thoughts?

**Comment by h3clikejava** [comment]
same

**Comment by workpioupiou** [comment]
same

**Comment by Oyiyi** [comment]
Anyone here solved it yet? Thank you!
