### ISSUE TITLE
How to get camera matrix based on reference orbits (What is the radius)

### ISSUE THREAD

**Issue by yuchenrao** [Stability-AI/generative-models#342]
Thanks a lot for the great work!

Since the 3D reconstruction code has not been released yet, I am planning to write my own work. However I am still not sure about how to get correct camera matrix. We already know FOV is 33.8 and image size as 576*576, which can be used for generating intrinsic matrix. We know azimuths_rad and polar_rad for extrinsic matrix, but we still missing the radius information. How can I get this information?

It would also be really nice if you could release this script for better clarification. 

Thank you very much!

Best,
Yuchen

**Comment by LeFou-k** [comment]
The same question here.

**Comment by kszpxxzmc** [comment]
The same question here.

**Comment by JanRiebe** [comment]
The same question here :)

**Comment by Seunggyu-Lee** [comment]
Same question here! Anyone solved?

**Comment by chunhanyao-stable** [comment]
Our default radius is 2.
