### ISSUE TITLE
UnboundLocalError: local variable 'input_image' referenced before assignment

### ISSUE THREAD

**Issue by qiuyuzhao** [Stability-AI/generative-models#361]
run python scripts/sampling/simple_video_sample.py --version svd_xt, An error message is displayed   UnboundLocalError: local variable 'input_image' referenced before assignment

**Comment by Benjamin-So** [comment]
Hi I had the same issue. Were you able to resolve it?

**Comment by yxxshin** [comment]
Hope you figured it out. For people watching this: the `input_image` is not handled correctly when `image.mode != "RGBA"`.  Just simply change:

```python
if image.mode == "RGBA":
    input_image = image.convert("RGB")
```

to:

```python
input_image = image.convert("RGB")
```
