### ISSUE TITLE
how to train sv3d

### ISSUE THREAD

**Issue by shewangmu** [Stability-AI/generative-models#380]
Is there any training script I can use to fintune sv3d on my own dataset?

**Comment by erceguder** [comment]
The same question here. I am looking forward for training configurations regarding SV3D. Thank you!

**Comment by erceguder** [comment]
Hey @shewangmu, I see that you've closed the issue. Did you find anything helpful? If so, could you share it with the community?

**Comment by shewangmu** [comment]
> Hey @shewangmu, I see that you've closed the issue. Did you find anything helpful? If so, could you share it with the community?

sorry, I don't. I just think the training scripts won't be published. Some svd training scripts might be helpful.
