### ISSUE TITLE
where is the checkpoint of encoder of sv3d

### ISSUE THREAD

**Issue by shewangmu** [Stability-AI/generative-models#395]
The checkpoint of sv3d/sv4d only includes the decoder. Where can I find the corresponding weights of encoder.

**Comment by danier97** [comment]
Hi @shewangmu, did you figure this out?

**Comment by shewangmu** [comment]
> Hi @shewangmu, did you figure this out?
I think it might be the same as the embedder of the cond frame

**Comment by danier97** [comment]
Yes I think you are right. Thanks!
