### ISSUE TITLE
.ckpt file is missing from HF repository

### ISSUE THREAD

**Issue by spuliz** [Stability-AI/generative-models#40]
Hi there,

I would like to fine tune your model using dreambooth. 
Is it possible to get the .ckpt model file?

Cheers,
S.

**Comment by jenuk** [comment]
We will not be distributing `.ckpt` files in the future, as they may contain arbitrary code and are a risk to end-users. The `.safetensors` file contains all needed weights to run and finetune SDXL. Instead, we recommend to update your finetuning library to work with `safetensors` instead, this will likely only require you to change a single line, see here:

https://github.com/Stability-AI/generative-models/blob/e5dc9669eddacb6606ac08f7e11dcf452e636bfe/sgm/models/diffusion.py#L89-L92
