### ISSUE TITLE
AUTOMATIC1111 1.5 wont load sdxl, hangs then reselects sd1.5

### ISSUE THREAD

**Issue by emmanceb** [Stability-AI/generative-models#75]
I'm running this on Paperspace on an A6000, eventually selecting sdxl results in a connection errored out message and I have to relaunch webui. Yes i have the VAE and refiner.

**Comment by akx** [comment]
This isn't the repo to report this – report it at https://github.com/AUTOMATIC1111/stable-diffusion-webui instead, using the bug report template there.

**Comment by jenuk** [comment]
As akx has said, this is not an issue with our codebase, please report at the webui-repositroy.

**Comment by SongDI911** [comment]
maybe you can see this 
https://www.youtube.com/watch?v=eY_v5IR4dUQ
