### ISSUE TITLE
Question: How to use SDXL 1.0 Refiner in Python Script?

### ISSUE THREAD

**Issue by MinervaArgus** [Stability-AI/generative-models#84]
I understand how to use the Base in Python code but I do not understand how to pass an image to the refiner in Python. Can someone please help?

**Comment by huajianmao** [comment]
[Diffusers document](https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_xl#stable-diffusion-xl) gives some examples.

``` python
from diffusers import DiffusionPipeline
import torch

base = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
base.to("cuda")

refiner = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-refiner-1.0",
    text_encoder_2=base.text_encoder_2,
    vae=base.vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)
refiner.to("cuda")
```

**Comment by MinervaArgus** [comment]
Thank you so much!

**Comment by Jonisa2022** [comment]
import refiner
# Load the image
image = cv2.imread("image.jpg")
# Create a refiner object
refiner = refiner.Refiner()
# Pass the image to the refiner
refiner.process(image)
# Save the refined image
refiner.save("refined_image.jpg")

**Comment by Jonisa2022** [comment]
import refiner
# Load the image
image = cv2.imread("image.jpg")
# Create a refiner object
refiner = refiner.Refiner()
# Pass the image to the refiner
refiner.process(image)
# Save the refined image
refiner.save("refined_image.jpg")
