### ISSUE TITLE
How to get stable-datasets?

### ISSUE THREAD

**Issue by johngull** [Stability-AI/generative-models#91]
I wanted to check toy training examples. But faced a problem in that it requires a `stable-datasets` submodule which is not accessible.
Please assist in getting this module.

Thanks.

**Comment by jenuk** [comment]
The module should be `sdata` and can be installed as descrbied [here](https://github.com/Stability-AI/generative-models#4-install-sdata-for-training) in the readme. Did you do that part of the installation instructions? If so, can you point me to the part of the code that causes you problems?

**Comment by johngull** [comment]
Oh. My fault. 
I missed this step in the readme.

I was able to install it but without the "-e" key.

Thank you a lot for assisting.

**Comment by jueer33** [comment]
```
try:
    from sdata import create_dataset, create_dummy_dataset, create_loader
except ImportError as e:
    print("#" * 100)
    print("Datasets not yet available")
    print("to enable, we need to add stable-datasets as a submodule")
    print("please use ``git submodule update --init --recursive``")
    print("and do ``pip install -e stable-datasets/`` from the root of this repo")
    print("#" * 100)
    exit(1)
```

    This part of the code is throwing an error, but I've already installed `sdata`. What should I do?
